openapi: 3.0.1
info:
  title: get-s3
  description: service that gets files from S3
  version: 1.0.0
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT

paths:
  /getS3/{modelPath}:
    get:
      operationId: getList
      tags:
        - S3
      summary: gets the files
      parameters:
        - $ref: '#/components/parameters/modelPath'
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/content'
        400:
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error'
components:
  parameters:
    modelPath:
      in: path
      name: modelPath
      required: true
      schema:
        type: string
      description: The 3d model name
  schemas:
    error:
      type: object
      required:
        - message
      properties:
        message:
          type: string
    content:
      type: array
